# Application configuration
server:
  port: 8096
spring:
  application:
    name: notification

# Eureka client configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka
